#!/bin/bash
filename=/etc/nix-setup-check-file

if [[ -f "$nix-setup-check-file" ]];

then

echo "Preparing nix installation script..."

sleep 5

sudo echo "Preparing nix installer..."

sleep 5

sh <(curl -L https://nixos.org/nix/install) --no-daemon

echo "Modifying configs..."
sleep 1
sudo rm -f /etc/nix/nix.conf ; sudo wget -P /etc/nix https://raw.githubusercontent.com/dnkmmr69420/nix-installer-scripts/main/nix-distrobox/nix.conf
sudo rm -f /etc/profile.d/nix-app-icons.sh ; sudo wget -P /etc/profile.d https://raw.githubusercontent.com/dnkmmr69420/nix-installer-scripts/main/other-files/nix-app-icons.sh
sudo touch /etc/nix-setup-check-file

else

exit 0

fi
